#!/bin/bash

mvn clean deploy
mvn release:clean
git commit -a -m "version bump"
git push origin master
mvn release:prepare
mvn release:perform

# Note: Be sure that the local Maven settings.xml file is configured with the right credentials, and that the system has the right GPG keys installed (along with a valid GPG installation)

# Now go to https://oss.sonatype.org/index.html and release it
