#!/bin/bash

mvn clean deploy
mvn release:clean
git commit -a -m "version bump"
git push origin master
mvn release:prepare
mvn release:perform

# Now go to https://oss.sonatype.org/index.html and release it
