package io.github.openunirest.http.options;

public enum Option {
	HTTPCLIENT,
	ASYNCHTTPCLIENT,
	CONNECTION_TIMEOUT,
	SOCKET_TIMEOUT,
	DEFAULT_HEADERS,
	SYNC_MONITOR,
	ASYNC_MONITOR,
	MAX_TOTAL,
	MAX_PER_ROUTE,
	PROXY,
	OBJECT_MAPPER,
	FOLLOW_REDIRECTS,
	COOKIE_MANAGEMENT
}
